version: "3"

services:
    focalboard-nginx-backup:
        image: postgres:$POSTGRES_VERSION
        container_name: website-focalboard-nginx-backup
        entrypoint: tar
        command:
            - -zcf
            - /root/backup/nginx-backup.tar.gz
            - -C/etc/nginx/
            - conf.d/
            - cert.d/
        volumes:
            - nginx-confs:/etc/nginx/conf.d
            - nginx-certs:/etc/nginx/cert.d
            - $BASE_PATH/backup:/root/backup
        networks:
            - focalboard

    focalboard-nginx-restore:
        image: postgres:$POSTGRES_VERSION
        container_name: website-focalboard-nginx-restore
        entrypoint: tar
        command:
            - -zxf
            - /root/backup/nginx-backup.tar.gz
            - -C/etc/nginx/
        volumes:
            - nginx-confs:/etc/nginx/conf.d
            - nginx-certs:/etc/nginx/cert.d
            - $BASE_PATH/backup:/root/backup
        networks:
            - focalboard

networks:
    focalboard:
        name: website-focalboard

volumes:
    nginx-confs:
        name: website-nginx-confs
        external: true

    nginx-certs:
        name: website-nginx-certs
        external: true
