version: "3"

services:
    focalboard-server-backup:
        image: postgres:$POSTGRES_VERSION
        container_name: website-focalboard-server-backup
        entrypoint: tar
        command:
            - -zcf
            - /root/backup/focalboard-server-backup.tar.gz
            - -C/opt/focalboard/
            - files
        volumes:
            - focalboard-server-files:/opt/focalboard/files
            - $BASE_PATH/backup:/root/backup
        networks:
            - focalboard

    focalboard-server-restore:
        image: postgres:$POSTGRES_VERSION
        container_name: website-focalboard-server-restore
        entrypoint: tar
        command:
            - -zxf
            - /root/backup/focalboard-server-backup.tar.gz
            - -C/opt/focalboard/
        volumes:
            - focalboard-server-files:/opt/focalboard/files
            - $BASE_PATH/backup:/root/backup
        networks:
            - focalboard

networks:
    focalboard:
        name: website-focalboard

volumes:
    focalboard-server-files:
        name: website-focalboard-server-files
