version: "3"

services:
    nginx:
        image: nginx:$NGINX_VERSION
        container_name: khose-ie-nginx
        restart: unless-stopped
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443
        volumes:
            - khose-ie-nginx-confs:/etc/nginx/conf.d
            - khose-ie-nginx-certs:/etc/nginx/cert.d
        networks:
            - nginx
            - khose-ie

networks:
    nginx:
        name: khose-ie-nginx

    khose-ie:
        name: khose-ie
        external: true

volumes:
    khose-ie-nginx-confs:
        name: khose-ie-nginx-confs

    khose-ie-nginx-certs:
        name: khose-ie-nginx-certs
