version: "3"

services:
    nginx:
        image: nginx:$NGINX_VERSION
        container_name: website-nginx
        restart: unless-stopped
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443
        volumes:
            - nginx-confs:/etc/nginx/conf.d
            - nginx-certs:/etc/nginx/cert.d
        networks:
            - nginx
            - website

networks:
    nginx:
        name: website-nginx

    website:
        name: website
        external: true

volumes:
    nginx-confs:
        name: website-nginx-confs

    nginx-certs:
        name: website-nginx-certs
