version: "3"

services:
    nginx:
        image: nginx:$NGINX_VERSION
        container_name: website-nginx
        restart: unless-stopped
        environment:
            - BASE_URL=$BASE_URL
            - HOME_CERT=default
        volumes:
            - $BASE_PATH/containers/nginx/volume/bin/40-enable-apps.sh:/docker-entrypoint.d/40-enable-apps.sh
            - $BASE_PATH/containers/nginx/volume/config:/root/config
            - $BASE_PATH/certs:/root/certs
        networks:
            - nginx
            - website
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443

networks:
    nginx:
        name: website-nginx

    website:
        name: website
        external: true
