version: "3"

services:
    nginx:
        image: nginx:1.23-alpine
        container_name: website-nginx
        restart: unless-stopped
        environment:
            - HOME_URL=$HOME_URL
            - HOME_CERT=$HOME_CERT
            - REDMINE_NAME=redmine-server
            - REDMINE_PORT=3000
            - REDMINE_URL=$REDMINE_URL
            - REDMINE_CERT=$REDMINE_CERT
            - ONEDEV_NAME=onedev-server
            - ONEDEV_PORT=6610
            - ONEDEV_URL=$ONEDEV_URL
            - ONEDEV_CERT=$ONEDEV_CERT
        volumes:
            - $BASE_PATH/containers/nginx/volume/bin/40-enable-apps.sh:/docker-entrypoint.d/40-enable-apps.sh
            - $BASE_PATH/containers/nginx/volume/config:/root/config
            - $BASE_PATH/certs:/root/certs
        networks:
            - nginx
            - website
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443

networks:
    nginx:
        name: website-nginx

    website:
        name: website
        external: true
