version: "3"

services:
    nginx-server-backup:
        image: nginx:$NGINX_VERSION
        container_name: website-nginx-server-backup
        entrypoint: echo
        command:
            - NGINX have no data to backup.

    nginx-server-restore:
        image: nginx:$NGINX_VERSION
        container_name: website-nginx-server-restore
        entrypoint: echo
        command:
            - NGINX have no data to restore.

    nginx-server-enable:
        image: nginx:$NGINX_VERSION
        container_name: website-nginx-server-enable
        entrypoint: cp
        command:
            - /root/volume/default.conf
            - /root/volume/default.pem
            - /root/volume/default.key
            - /etc/nginx/conf.d
        volumes:
            - nginx-confd:/etc/nginx/conf.d
            - $BASE_PATH/volume/nginx:/root/volume
        networks:
            - nginx

    nginx-server-disable:
        image: nginx:$NGINX_VERSION
        container_name: website-nginx-server-disable
        entrypoint: rm
        command:
            - /etc/nginx/conf.d/default.conf
            - /etc/nginx/conf.d/default.pem
            - /etc/nginx/conf.d/default.key
        volumes:
            - nginx-confd:/etc/nginx/conf.d
        networks:
            - nginx

networks:
    nginx:
        name: website-nginx

volumes:
    nginx-confd:
        name: website-nginx-confd
