version: "3"

services:
    redmine-server:
        image: redmine:5.0.1-alpine
        container_name: website-redmine-server
        restart: unless-stopped
        environment:
            - REDMINE_DB_POSTGRES=redmine-database
            - REDMINE_DB_DATABASE=redmine
            - REDMINE_DB_USERNAME=redmine
            - REDMINE_DB_PASSWORD=redmine
            - REDMINE_SECRET_KEY_BASE=supersecretkey
        volumes:
            - $BASE_PATH/containers/redmine/volume/config/configuration.yml:/usr/src/redmine/config/configuration.yml
            - redmine-server:/usr/src/redmine/files
        depends_on:
            - redmine-database
        networks:
            - redmine
            - website

    redmine-database:
        image: postgres:14.4-alpine
        container_name: website-redmine-database
        restart: unless-stopped
        environment:
            - POSTGRES_DB=redmine
            - POSTGRES_USER=redmine
            - POSTGRES_PASSWORD=redmine
        volumes:
            - redmine-database:/var/lib/postgresql/data
        networks:
            - redmine

networks:
    redmine:
        name: website-redmine

    website:
        name: website
        external: true

volumes:
    redmine-server:
        name: website-redmine-server

    redmine-database:
        name: website-redmine-database
