version: "3"

services:
    redmine-server-backup:
        image: redmine:$REDMINE_VERSION
        container_name: website-redmine-server-backup
        entrypoint: tar
        command:
            - -zcf
            - /root/backup/redmine-server-backup.tar.gz
            - -C/usr/src/redmine/
            - files
        volumes:
            - redmine-server:/usr/src/redmine/files
            - $BASE_PATH/backup:/root/backup
        networks:
            - redmine

    redmine-server-restore:
        image: redmine:$REDMINE_VERSION 
        container_name: website-redmine-server-restore
        entrypoint: tar
        command:
            - -zxf
            - /root/backup/redmine-server-backup.tar.gz
            - -C/usr/src/redmine/
        volumes:
            - redmine-server:/usr/src/redmine/files
            - $BASE_PATH/backup:/root/backup
        networks:
            - redmine

    redmine-server-enable:
        image: redmine:$REDMINE_VERSION
        container_name: website-redmine-server-enable
        entrypoint: cp
        command:
            - /root/volume/redmine.conf
            - /root/volume/redmine.pem
            - /root/volume/redmine.key
            - /etc/nginx/conf.d
        volumes:
            - nginx-confd:/etc/nginx/conf.d
            - $BASE_PATH/volume/nginx:/root/volume
        networks:
            - redmine

    redmine-server-disable:
        image: redmine:$REDMINE_VERSION
        container_name: website-redmine-server-disable
        entrypoint: rm
        command:
            - /etc/nginx/conf.d/redmine.conf
            - /etc/nginx/conf.d/redmine.pem
            - /etc/nginx/conf.d/redmine.key
        volumes:
            - nginx-confd:/etc/nginx/conf.d
        networks:
            - redmine

networks:
    redmine:
        name: website-redmine

volumes:
    redmine-server:
        name: website-redmine-server

    nginx-confd:
        name: website-nginx-confd
        external: true
