version: "3"

services:
    onedev-server:
        image: 1dev/server:7.2.5
        container_name: website-onedev-server
        restart: unless-stopped
        volumes:
            - onedev-server:/opt/onedev
        depends_on:
            - onedev-database
        networks:
            - onedev
            - website

    onedev-database:
        image: postgres:14.4-alpine
        container_name: website-onedev-database
        restart: unless-stopped
        environment:
            - POSTGRES_DB=onedev
            - POSTGRES_USER=onedev
            - POSTGRES_PASSWORD=onedev
        volumes:
            - onedev-database:/var/lib/postgresql/data
        networks:
            - onedev

    # onedev-agent:
    #     image: 1dev/agent:latest
    #     container_name: website-onedev-agent
    #     restart: unless-stopped
    #     hostname: host-agent
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     environment:
    #         - serverUrl=onedev-server:6610
    #         - agentToken=
    #     networks:
    #         - onedev

networks:
    onedev:
        name: website-onedev

    website:
        name: website
        external: true

volumes:
    onedev-server:
        name: website-onedev-server

    onedev-database:
        name: website-onedev-database
