version: "3"

services:
    onedev-agent:
        image: 1dev/agent:latest
        container_name: website-onedev-agent
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        hostname: default-agent
        environment:
            - serverUrl=onedev-server:6610
            - agentToken=
        networks:
            - onedev

networks:
    onedev:
        name: website-onedev

