version: "3"

services:
    onedev-database-backup:
        image: 1dev/server:$ONEDEV_VERSION
        container_name: khose-ie-onedev-database-backup
        entrypoint: /opt/onedev/bin/backup-db.sh
        command: /root/backup/database-backup.zip
        links: 
            - onedev-server
        volumes:
            - onedev-server:/opt/onedev
            - $BASE_PATH/backup:/root/backup
        depends_on:
            - onedev-server
            - onedev-database
        networks:
            - onedev

    onedev-database-restore:
        image: 1dev/server:$ONEDEV_VERSION
        container_name: khose-ie-onedev-database-restore
        entrypoint: /opt/onedev/bin/restore-db.sh
        command: /root/backup/database-backup.zip
        volumes:
            - onedev-server:/opt/onedev
            - $BASE_PATH/backup:/root/backup
        depends_on:
            - onedev-database
        networks:
            - onedev

networks:
    onedev:
        name: khose-ie-onedev

volumes:
    onedev-server:
        name: khose-ie-onedev-server
